# Generated by Django 4.1.6 on 2023-07-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('du2', '0004_rename_post_comment_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posts',
            new_name='post',
        ),
    ]
